services:
  server:
    image: novadityap/blog-app-server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    restart: always

  client:
    image: novadityap/blog-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:80"
    restart: always

