services:
  blog-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: blog-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
