services:
  blog-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: novadityap/blog-app:v1.0.0
    container_name: blog-app
    ports:
      - "3000:3000"
    env_file:
      - .env
